#!/usr/bin/env node --experimental-strip-types
/**
 * Prints the projects.public_holidays VALUES block for a range of years,
 * derived from listHolidaysNamed(). The seed in the migration is GENERATED by
 * this script and never hand-typed — Appendix A(h) requires the table be a
 * materialisation of the computus, not a second source of truth.
 *
 *   node --experimental-strip-types scripts/db/gen-public-holidays-seed.ts 2024 2035
 *
 * The horizon matters: projects.working_days_between RAISES on an unseeded
 * year with no fallback to calendar days, so the last seeded year is the year
 * after which every due-date computation in the product throws.
 */
import { listHolidaysNamed } from '../../packages/shared/src/lib/jbcc/sa-public-holidays.ts'

const from = Number(process.argv[2] ?? 2024)
const to = Number(process.argv[3] ?? 2035)

const rows: string[] = []
for (let y = from; y <= to; y++) {
  for (const h of listHolidaysNamed(y)) {
    rows.push(`  ('${h.date.toISOString().slice(0, 10)}', '${h.name.replace(/'/g, "''")}')`)
  }
}
rows.sort()

console.log(`INSERT INTO projects.public_holidays (d, name) VALUES`)
console.log(rows.join(',\n'))
console.log(`ON CONFLICT (d) DO NOTHING;`)
console.log()
console.log(`INSERT INTO projects.calendar_years (year)`)
console.log(`SELECT generate_series(${from}, ${to})`)
console.log(`ON CONFLICT (year) DO NOTHING;`)
