import { headers } from 'next/headers'
import { NextResponse } from 'next/server'
import type { EmailOtpType } from '@supabase/supabase-js'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import { logAuthEvent } from '@esite/shared'
import { THEME_COOKIE, THEME_COOKIE_MAX_AGE } from '@/lib/theme/types'
import type { SupabaseClient } from '@supabase/supabase-js'
import type { Database } from '@esite/db'

const VALID_OTP_TYPES: ReadonlySet<EmailOtpType> = new Set([
  'signup',
  'invite',
  'magiclink',
  'recovery',
  'email_change',
  'email',
])

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url)
  const code = searchParams.get('code')
  const tokenHash = searchParams.get('token_hash') ?? searchParams.get('token')
  const otpTypeRaw = searchParams.get('type')
  const next = searchParams.get('next') ?? '/dashboard'
  // Supabase redirects back with these when its /verify endpoint rejects
  // the token (expired, already-used, or burned by an email scanner).
  const errorCode = searchParams.get('error_code')
  // `from` annotates the caller: 'magic_link', 'oauth_google', etc.
  const from = searchParams.get('from')

  // If Supabase bounced with an error_code, route the user straight to the
  // code-entry page with email pre-filled (if we have it) so they can type
  // the code from the same email without restarting the flow.
  if (errorCode) {
    const carriedEmail = searchParams.get('email')
    console.warn('auth/callback: supabase error_code', { errorCode, next, hasEmail: !!carriedEmail })
    if (next.startsWith('/reset-password')) {
      const params = new URLSearchParams({ step: 'code', error: errorCode })
      if (carriedEmail) params.set('email', carriedEmail)
      return NextResponse.redirect(`${origin}/reset-password?${params.toString()}`)
    }
    const params = new URLSearchParams({ error: errorCode })
    if (carriedEmail) params.set('email', carriedEmail)
    return NextResponse.redirect(`${origin}/login?${params.toString()}`)
  }

  const supabase = await createClient()

  // PKCE flow — links generated by client-side @supabase/ssr browser
  // helpers carry ?code=PKCE_CODE.
  if (code) {
    const { error, data } = await supabase.auth.exchangeCodeForSession(code)
    if (!error) {
      await auditLogin(data.user?.id ?? null, from)
      return await redirectWithTheme(supabase, data.user?.id ?? null, `${origin}${next}`)
    }
    console.error('auth/callback: exchangeCodeForSession failed', error)
  }

  // OTP flow — Supabase Auth emails default to ?token_hash=...&type=recovery
  // when the project isn't on PKCE. Same handler signature regardless.
  if (tokenHash && otpTypeRaw && VALID_OTP_TYPES.has(otpTypeRaw as EmailOtpType)) {
    const { error, data } = await supabase.auth.verifyOtp({
      token_hash: tokenHash,
      type:       otpTypeRaw as EmailOtpType,
    })
    if (!error) {
      // verifyOtp counts as a login for password-reset / magic-link / signup;
      // for 'email_change' the audit is already handled by changeEmailAction.
      if (otpTypeRaw !== 'email_change') {
        await auditLogin(data.user?.id ?? null, from ?? otpTypeRaw)
      }
      return await redirectWithTheme(supabase, data.user?.id ?? null, `${origin}${next}`)
    }
    console.error('auth/callback: verifyOtp failed', error)
  }

  return NextResponse.redirect(`${origin}/login?error=auth_callback_failed`)
}

async function auditLogin(userId: string | null, from: string | null): Promise<void> {
  if (!userId || from === 'email_change_confirmation') return
  const headersList = await headers()
  const ip = headersList.get('x-forwarded-for')?.split(',')[0]?.trim() ?? null
  const ua = headersList.get('user-agent') ?? null
  await logAuthEvent(createServiceClient(), {
    userId,
    eventType: 'login',
    ipAddress: ip,
    userAgent: ua,
    metadata:  { method: from ?? 'callback' },
  })
}

// Seed the theme cookie from the user's saved preference so a fresh device
// renders the correct theme on the very next request (cross-device sync).
async function redirectWithTheme(
  supabase: SupabaseClient<Database>,
  userId: string | null,
  url: string,
) {
  const res = NextResponse.redirect(url)
  if (userId) {
    const { data } = await supabase.from('profiles')
      .select('theme_preference').eq('id', userId).single()
    const mode = data?.theme_preference
    if (mode === 'light' || mode === 'dark' || mode === 'system') {
      res.cookies.set(THEME_COOKIE, mode, {
        path: '/', maxAge: THEME_COOKIE_MAX_AGE, sameSite: 'lax',
      })
    }
  }
  return res
}
