// Auto-generated by: pnpm db:gen-types
// Run: supabase gen types typescript --local > packages/db/src/types.ts
// DO NOT EDIT MANUALLY

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Populated after: pnpm db:gen-types
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
