-- Site-scoped access. GENERATED by scripts/db/site-scope/emit.ts from
-- packages/db/src/site-scope/{manifest,fixed.sql}.ts. Do not edit by hand.
-- Spec: docs/superpowers/specs/2026-10-01-site-scoped-access-design.md
-- @verify:begin
-- sql: (SELECT pg_get_functiondef('public.user_has_project_access(uuid)'::regprocedure) NOT LIKE '%project_manager%')
-- sql: (SELECT pg_get_functiondef('public.user_effective_project_role(uuid,uuid)'::regprocedure) NOT LIKE '%project_manager%')
-- policy: site_scope ON projects.projects RESTRICTIVE
-- policy: site_scope ON public.profiles RESTRICTIVE
-- policy: site_scope_objects ON storage.objects RESTRICTIVE
-- function: public.user_has_project_access(uuid)
-- function: public.user_effective_project_role(uuid, uuid)
-- function: public.custom_jwt_claims(jsonb)
-- function: public.storage_site_access(text, text)
-- function: public.user_can_see_profile(uuid)
-- sql: (SELECT NOT has_function_privilege('anon', 'public.storage_site_access(text,text)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.user_can_see_profile(uuid)', 'EXECUTE'))
-- sql: (SELECT pg_get_functiondef('public.custom_jwt_claims(jsonb)'::regprocedure) LIKE '%all_sites%')
-- function: public.site_project_of_site_diary_entry(uuid)
-- function: public.site_project_of_jbcc_letter(uuid)
-- function: public.site_project_of_node(uuid)
-- function: public.site_project_of_node_order(uuid)
-- function: public.site_project_of_tenant_document(uuid)
-- function: public.site_project_of_work_item(uuid)
-- function: public.site_project_of_boq_import(uuid)
-- function: public.site_project_of_boq_section(uuid)
-- function: public.site_project_of_rfi(uuid)
-- function: public.site_project_of_gcr_zone(uuid)
-- function: public.site_project_of_snag(uuid)
-- function: public.site_project_of_floor_plan(uuid)
-- function: public.site_project_of_status_plan(uuid)
-- function: public.site_project_of_variation_order(uuid)
-- function: public.site_project_of_valuation(uuid)
-- function: public.site_project_of_qc_report(uuid)
-- function: public.site_project_of_revision(uuid)
-- function: public.site_project_of_supply_route(uuid)
-- function: public.site_project_of_cable(uuid)
-- function: public.site_project_of_inspection(uuid)
-- function: public.site_project_of_site_form(uuid)
-- function: public.site_project_of_tender(uuid)
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_site_diary_entry(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_jbcc_letter(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_node(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_node_order(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_tenant_document(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_work_item(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_boq_import(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_boq_section(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_rfi(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_gcr_zone(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_snag(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_floor_plan(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_status_plan(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_variation_order(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_valuation(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_qc_report(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_revision(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_supply_route(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_cable(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_inspection(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_site_form(uuid)', 'EXECUTE'))
-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_tender(uuid)', 'EXECUTE'))
-- policy: site_scope ON projects.jbcc_letters RESTRICTIVE
-- policy: site_scope ON projects.reports RESTRICTIVE
-- policy: site_scope ON field.snag_visits RESTRICTIVE
-- policy: site_scope ON gcr.settings RESTRICTIVE
-- policy: site_scope ON projects.project_members RESTRICTIVE
-- policy: site_scope ON projects.rfis RESTRICTIVE
-- policy: site_scope ON projects.drawings RESTRICTIVE
-- policy: site_scope ON projects.contacts RESTRICTIVE
-- policy: site_scope ON projects.handover_checklist RESTRICTIVE
-- policy: site_scope ON gcr.zones RESTRICTIVE
-- policy: site_scope ON gcr.tenant_assignments RESTRICTIVE
-- policy: site_scope ON projects.site_diary_entries RESTRICTIVE
-- policy: site_scope ON field.cables RESTRICTIVE
-- policy: site_scope ON field.inspection_milestones RESTRICTIVE
-- policy: site_scope ON field.inspection_requests RESTRICTIVE
-- policy: site_scope ON projects.jbcc_parties RESTRICTIVE
-- policy: site_scope ON field.snags RESTRICTIVE
-- policy: site_scope ON gcr.report_revisions RESTRICTIVE
-- policy: site_scope ON projects.variation_orders RESTRICTIVE
-- policy: site_scope ON tenants.handover_folders RESTRICTIVE
-- policy: site_scope ON projects.project_settings_history RESTRICTIVE
-- policy: site_scope ON tenants.documents RESTRICTIVE
-- policy: site_scope ON structure.nodes RESTRICTIVE
-- policy: site_scope ON projects.work_item_events RESTRICTIVE
-- policy: site_scope ON tenants.floor_plans RESTRICTIVE
-- policy: site_scope ON cable_schedule.sans_overrides RESTRICTIVE
-- policy: site_scope ON tenants.floor_plan_versions RESTRICTIVE
-- policy: site_scope ON structure.node_orders RESTRICTIVE
-- policy: site_scope ON projects.qc_entries RESTRICTIVE
-- policy: site_scope ON projects.valuations RESTRICTIVE
-- policy: site_scope ON projects.qc_reports RESTRICTIVE
-- policy: site_scope ON projects.qc_entry_photos RESTRICTIVE
-- policy: site_scope ON projects.work_item_notes RESTRICTIVE
-- policy: site_scope ON projects.work_item_attachments RESTRICTIVE
-- policy: site_scope ON projects.boq_imports RESTRICTIVE
-- policy: site_scope ON tenants.cloud_sync_runs RESTRICTIVE
-- policy: site_scope ON cable_schedule.revisions RESTRICTIVE
-- policy: site_scope ON field.site_forms RESTRICTIVE
-- policy: site_scope ON inspections.inspections RESTRICTIVE
-- policy: site_scope ON tenants.floor_plan_markups RESTRICTIVE
-- policy: site_scope ON projects.load_profiles RESTRICTIVE
-- policy: site_scope ON projects.load_profile_sources RESTRICTIVE
-- policy: site_scope ON projects.work_items RESTRICTIVE
-- policy: site_scope ON projects.tenders RESTRICTIVE
-- policy: site_scope ON projects.project_settings RESTRICTIVE
-- policy: site_scope ON tenants.status_plans RESTRICTIVE
-- policy: site_scope ON projects.site_diary_attachments RESTRICTIVE
-- policy: site_scope ON projects.jbcc_letter_events RESTRICTIVE
-- policy: site_scope ON projects.jbcc_letter_recipients RESTRICTIVE
-- policy: site_scope ON projects.jbcc_letter_attachments RESTRICTIVE
-- policy: site_scope ON structure.tenant_documents RESTRICTIVE
-- policy: site_scope ON structure.tenant_document_revisions RESTRICTIVE
-- policy: site_scope ON structure.tenant_units RESTRICTIVE
-- policy: site_scope ON structure.tenant_scope_items RESTRICTIVE
-- policy: site_scope ON structure.tenant_details RESTRICTIVE
-- policy: site_scope ON structure.node_circuits RESTRICTIVE
-- policy: site_scope ON structure.node_order_documents RESTRICTIVE
-- policy: site_scope ON structure.node_order_shop_drawings RESTRICTIVE
-- policy: site_scope ON projects.work_item_watchers RESTRICTIVE
-- policy: site_scope ON projects.boq_sections RESTRICTIVE
-- policy: site_scope ON projects.boq_items RESTRICTIVE
-- policy: site_scope ON projects.rfi_responses RESTRICTIVE
-- policy: site_scope ON public.rfi_annotations RESTRICTIVE
-- policy: site_scope ON gcr.zone_generators RESTRICTIVE
-- policy: site_scope ON field.snag_photos RESTRICTIVE
-- policy: site_scope ON tenants.floor_plan_zones RESTRICTIVE
-- policy: site_scope ON tenants.floor_plan_page_scales RESTRICTIVE
-- policy: site_scope ON tenants.status_plan_shapes RESTRICTIVE
-- policy: site_scope ON projects.variation_lines RESTRICTIVE
-- policy: site_scope ON projects.valuation_lines RESTRICTIVE
-- policy: site_scope ON projects.qc_comments RESTRICTIVE
-- policy: site_scope ON cable_schedule.route_history RESTRICTIVE
-- policy: site_scope ON cable_schedule.mv_study_settings RESTRICTIVE
-- policy: site_scope ON cable_schedule.fault_sources RESTRICTIVE
-- policy: site_scope ON cable_schedule.protection_devices RESTRICTIVE
-- policy: site_scope ON cable_schedule.cables RESTRICTIVE
-- policy: site_scope ON cable_schedule.change_log RESTRICTIVE
-- policy: site_scope ON cable_schedule.fault_results RESTRICTIVE
-- policy: site_scope ON cable_schedule.cost_lines RESTRICTIVE
-- policy: site_scope ON cable_schedule.discrimination_checks RESTRICTIVE
-- policy: site_scope ON cable_schedule.mv_study_signoff RESTRICTIVE
-- policy: site_scope ON cable_schedule.supply_routes RESTRICTIVE
-- policy: site_scope ON cable_schedule.sources RESTRICTIVE
-- policy: site_scope ON cable_schedule.supplies RESTRICTIVE
-- policy: site_scope ON cable_schedule.route_segments RESTRICTIVE
-- policy: site_scope ON cable_schedule.terminations RESTRICTIVE
-- policy: site_scope ON cable_schedule.cable_tags RESTRICTIVE
-- policy: site_scope ON inspections.response_history RESTRICTIVE
-- policy: site_scope ON inspections.signatures RESTRICTIVE
-- policy: site_scope ON inspections.coc_validations RESTRICTIVE
-- policy: site_scope ON inspections.certificates RESTRICTIVE
-- policy: site_scope ON inspections.responses RESTRICTIVE
-- policy: site_scope ON inspections.photos RESTRICTIVE
-- policy: site_scope ON field.form_photos RESTRICTIVE
-- policy: site_scope ON field.form_signatures RESTRICTIVE
-- policy: site_scope ON field.form_responses RESTRICTIVE
-- policy: site_scope ON field.form_response_history RESTRICTIVE
-- policy: site_scope ON projects.tender_boq_items RESTRICTIVE
-- policy: site_scope ON projects.tender_requirements RESTRICTIVE
-- policy: site_scope ON projects.tender_estimate_lines RESTRICTIVE
-- @verify:end

CREATE OR REPLACE FUNCTION public.user_has_project_access(_project_id uuid)
 RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER
 SET search_path TO 'public' SET row_security TO 'off'
AS $function$
  SELECT
    -- (a) an active membership row whose identity org membership is active (00204)
    EXISTS (
      SELECT 1 FROM projects.project_members pm
      JOIN public.user_organisations uo ON uo.user_id = pm.user_id AND uo.organisation_id = pm.organisation_id
      WHERE pm.project_id = _project_id AND pm.user_id = auth.uid() AND pm.is_active AND uo.is_active)
    -- (b) owner or admin of the project's org sees every site (site-scoped access)
    OR EXISTS (
      SELECT 1 FROM projects.projects p
      JOIN public.user_organisations uo ON uo.organisation_id = p.organisation_id
      WHERE p.id = _project_id AND uo.user_id = auth.uid() AND uo.is_active AND uo.role IN ('owner', 'admin'))
$function$;

CREATE OR REPLACE FUNCTION public.user_effective_project_role(p_project_id uuid, p_user_id uuid DEFAULT auth.uid())
 RETURNS text LANGUAGE sql STABLE SECURITY DEFINER
 SET search_path TO 'public' SET row_security TO 'off'
AS $function$
  WITH org AS (
    SELECT uo.role FROM projects.projects p
    JOIN public.user_organisations uo ON uo.organisation_id = p.organisation_id
    WHERE p.id = p_project_id AND uo.user_id = p_user_id AND uo.is_active = TRUE LIMIT 1
  ), pm AS (
    SELECT pm.role FROM projects.project_members pm
    WHERE pm.project_id = p_project_id AND pm.user_id = p_user_id AND pm.is_active = TRUE LIMIT 1
  )
  SELECT CASE
    WHEN (SELECT role FROM org) IN ('owner', 'admin') THEN (SELECT role FROM org)   -- org owner/admin: every site
    WHEN (SELECT role FROM pm) IS NOT NULL THEN (SELECT role FROM pm)               -- everyone else: their membership
    ELSE NULL
  END;
$function$;

CREATE OR REPLACE FUNCTION public.site_project_of_site_diary_entry(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM projects.site_diary_entries WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_site_diary_entry(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_site_diary_entry(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_jbcc_letter(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM projects.jbcc_letters WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_jbcc_letter(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_jbcc_letter(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_node(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM structure.nodes WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_node(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_node(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_node_order(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM structure.node_orders WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_node_order(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_node_order(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_tenant_document(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT public.site_project_of_node(node_id) FROM structure.tenant_documents WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_tenant_document(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_tenant_document(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_work_item(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM projects.work_items WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_work_item(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_work_item(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_boq_import(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM projects.boq_imports WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_boq_import(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_boq_import(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_boq_section(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT public.site_project_of_boq_import(import_id) FROM projects.boq_sections WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_boq_section(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_boq_section(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_rfi(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM projects.rfis WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_rfi(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_rfi(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_gcr_zone(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM gcr.zones WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_gcr_zone(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_gcr_zone(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_snag(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM field.snags WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_snag(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_snag(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_floor_plan(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM tenants.floor_plans WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_floor_plan(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_floor_plan(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_status_plan(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM tenants.status_plans WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_status_plan(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_status_plan(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_variation_order(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM projects.variation_orders WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_variation_order(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_variation_order(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_valuation(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM projects.valuations WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_valuation(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_valuation(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_qc_report(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM projects.qc_reports WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_qc_report(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_qc_report(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_revision(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM cable_schedule.revisions WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_revision(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_revision(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_supply_route(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT public.site_project_of_revision(revision_id) FROM cable_schedule.supply_routes WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_supply_route(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_supply_route(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_cable(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT public.site_project_of_revision(revision_id) FROM cable_schedule.cables WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_cable(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_cable(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_inspection(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM inspections.inspections WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_inspection(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_inspection(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_site_form(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM field.site_forms WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_site_form(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_site_form(uuid) TO authenticated, service_role;
CREATE OR REPLACE FUNCTION public.site_project_of_tender(p_id uuid)
 RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'
AS $f$ SELECT project_id FROM projects.tenders WHERE id = p_id $f$;
REVOKE ALL ON FUNCTION public.site_project_of_tender(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.site_project_of_tender(uuid) TO authenticated, service_role;

DROP POLICY IF EXISTS site_scope ON projects.jbcc_letters;
CREATE POLICY site_scope ON projects.jbcc_letters AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.reports;
CREATE POLICY site_scope ON projects.reports AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON field.snag_visits;
CREATE POLICY site_scope ON field.snag_visits AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON gcr.settings;
CREATE POLICY site_scope ON gcr.settings AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.project_members;
CREATE POLICY site_scope ON projects.project_members AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.rfis;
CREATE POLICY site_scope ON projects.rfis AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.drawings;
CREATE POLICY site_scope ON projects.drawings AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.contacts;
CREATE POLICY site_scope ON projects.contacts AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.handover_checklist;
CREATE POLICY site_scope ON projects.handover_checklist AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON gcr.zones;
CREATE POLICY site_scope ON gcr.zones AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON gcr.tenant_assignments;
CREATE POLICY site_scope ON gcr.tenant_assignments AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.site_diary_entries;
CREATE POLICY site_scope ON projects.site_diary_entries AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON field.cables;
CREATE POLICY site_scope ON field.cables AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON field.inspection_milestones;
CREATE POLICY site_scope ON field.inspection_milestones AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON field.inspection_requests;
CREATE POLICY site_scope ON field.inspection_requests AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.jbcc_parties;
CREATE POLICY site_scope ON projects.jbcc_parties AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON field.snags;
CREATE POLICY site_scope ON field.snags AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON gcr.report_revisions;
CREATE POLICY site_scope ON gcr.report_revisions AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.variation_orders;
CREATE POLICY site_scope ON projects.variation_orders AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON tenants.handover_folders;
CREATE POLICY site_scope ON tenants.handover_folders AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.project_settings_history;
CREATE POLICY site_scope ON projects.project_settings_history AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON tenants.documents;
CREATE POLICY site_scope ON tenants.documents AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON structure.nodes;
CREATE POLICY site_scope ON structure.nodes AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.work_item_events;
CREATE POLICY site_scope ON projects.work_item_events AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON tenants.floor_plans;
CREATE POLICY site_scope ON tenants.floor_plans AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON cable_schedule.sans_overrides;
CREATE POLICY site_scope ON cable_schedule.sans_overrides AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON tenants.floor_plan_versions;
CREATE POLICY site_scope ON tenants.floor_plan_versions AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON structure.node_orders;
CREATE POLICY site_scope ON structure.node_orders AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.qc_entries;
CREATE POLICY site_scope ON projects.qc_entries AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.valuations;
CREATE POLICY site_scope ON projects.valuations AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.qc_reports;
CREATE POLICY site_scope ON projects.qc_reports AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.qc_entry_photos;
CREATE POLICY site_scope ON projects.qc_entry_photos AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.work_item_notes;
CREATE POLICY site_scope ON projects.work_item_notes AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.work_item_attachments;
CREATE POLICY site_scope ON projects.work_item_attachments AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.boq_imports;
CREATE POLICY site_scope ON projects.boq_imports AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON tenants.cloud_sync_runs;
CREATE POLICY site_scope ON tenants.cloud_sync_runs AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON cable_schedule.revisions;
CREATE POLICY site_scope ON cable_schedule.revisions AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON field.site_forms;
CREATE POLICY site_scope ON field.site_forms AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON inspections.inspections;
CREATE POLICY site_scope ON inspections.inspections AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON tenants.floor_plan_markups;
CREATE POLICY site_scope ON tenants.floor_plan_markups AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.load_profiles;
CREATE POLICY site_scope ON projects.load_profiles AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.load_profile_sources;
CREATE POLICY site_scope ON projects.load_profile_sources AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.work_items;
CREATE POLICY site_scope ON projects.work_items AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.tenders;
CREATE POLICY site_scope ON projects.tenders AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.project_settings;
CREATE POLICY site_scope ON projects.project_settings AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON tenants.status_plans;
CREATE POLICY site_scope ON tenants.status_plans AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(project_id))
  WITH CHECK (public.user_has_project_access(project_id));
DROP POLICY IF EXISTS site_scope ON projects.site_diary_attachments;
CREATE POLICY site_scope ON projects.site_diary_attachments AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_site_diary_entry(diary_entry_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_site_diary_entry(diary_entry_id)));
DROP POLICY IF EXISTS site_scope ON projects.jbcc_letter_events;
CREATE POLICY site_scope ON projects.jbcc_letter_events AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_jbcc_letter(letter_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_jbcc_letter(letter_id)));
DROP POLICY IF EXISTS site_scope ON projects.jbcc_letter_recipients;
CREATE POLICY site_scope ON projects.jbcc_letter_recipients AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_jbcc_letter(letter_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_jbcc_letter(letter_id)));
DROP POLICY IF EXISTS site_scope ON projects.jbcc_letter_attachments;
CREATE POLICY site_scope ON projects.jbcc_letter_attachments AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_jbcc_letter(letter_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_jbcc_letter(letter_id)));
DROP POLICY IF EXISTS site_scope ON structure.tenant_documents;
CREATE POLICY site_scope ON structure.tenant_documents AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_node(node_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_node(node_id)));
DROP POLICY IF EXISTS site_scope ON structure.tenant_document_revisions;
CREATE POLICY site_scope ON structure.tenant_document_revisions AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_tenant_document(tenant_document_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_tenant_document(tenant_document_id)));
DROP POLICY IF EXISTS site_scope ON structure.tenant_units;
CREATE POLICY site_scope ON structure.tenant_units AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_node(node_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_node(node_id)));
DROP POLICY IF EXISTS site_scope ON structure.tenant_scope_items;
CREATE POLICY site_scope ON structure.tenant_scope_items AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_node(node_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_node(node_id)));
DROP POLICY IF EXISTS site_scope ON structure.tenant_details;
CREATE POLICY site_scope ON structure.tenant_details AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_node(node_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_node(node_id)));
DROP POLICY IF EXISTS site_scope ON structure.node_circuits;
CREATE POLICY site_scope ON structure.node_circuits AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_node(node_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_node(node_id)));
DROP POLICY IF EXISTS site_scope ON structure.node_order_documents;
CREATE POLICY site_scope ON structure.node_order_documents AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_node_order(node_order_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_node_order(node_order_id)));
DROP POLICY IF EXISTS site_scope ON structure.node_order_shop_drawings;
CREATE POLICY site_scope ON structure.node_order_shop_drawings AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_node_order(node_order_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_node_order(node_order_id)));
DROP POLICY IF EXISTS site_scope ON projects.work_item_watchers;
CREATE POLICY site_scope ON projects.work_item_watchers AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_work_item(work_item_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_work_item(work_item_id)));
DROP POLICY IF EXISTS site_scope ON projects.boq_sections;
CREATE POLICY site_scope ON projects.boq_sections AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_boq_import(import_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_boq_import(import_id)));
DROP POLICY IF EXISTS site_scope ON projects.boq_items;
CREATE POLICY site_scope ON projects.boq_items AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_boq_section(section_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_boq_section(section_id)));
DROP POLICY IF EXISTS site_scope ON projects.rfi_responses;
CREATE POLICY site_scope ON projects.rfi_responses AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_rfi(rfi_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_rfi(rfi_id)));
DROP POLICY IF EXISTS site_scope ON public.rfi_annotations;
CREATE POLICY site_scope ON public.rfi_annotations AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_rfi(rfi_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_rfi(rfi_id)));
DROP POLICY IF EXISTS site_scope ON gcr.zone_generators;
CREATE POLICY site_scope ON gcr.zone_generators AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_gcr_zone(zone_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_gcr_zone(zone_id)));
DROP POLICY IF EXISTS site_scope ON field.snag_photos;
CREATE POLICY site_scope ON field.snag_photos AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_snag(snag_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_snag(snag_id)));
DROP POLICY IF EXISTS site_scope ON tenants.floor_plan_zones;
CREATE POLICY site_scope ON tenants.floor_plan_zones AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_floor_plan(floor_plan_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_floor_plan(floor_plan_id)));
DROP POLICY IF EXISTS site_scope ON tenants.floor_plan_page_scales;
CREATE POLICY site_scope ON tenants.floor_plan_page_scales AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_floor_plan(floor_plan_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_floor_plan(floor_plan_id)));
DROP POLICY IF EXISTS site_scope ON tenants.status_plan_shapes;
CREATE POLICY site_scope ON tenants.status_plan_shapes AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_status_plan(status_plan_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_status_plan(status_plan_id)));
DROP POLICY IF EXISTS site_scope ON projects.variation_lines;
CREATE POLICY site_scope ON projects.variation_lines AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_variation_order(variation_order_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_variation_order(variation_order_id)));
DROP POLICY IF EXISTS site_scope ON projects.valuation_lines;
CREATE POLICY site_scope ON projects.valuation_lines AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_valuation(valuation_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_valuation(valuation_id)));
DROP POLICY IF EXISTS site_scope ON projects.qc_comments;
CREATE POLICY site_scope ON projects.qc_comments AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_qc_report(report_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_qc_report(report_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.route_history;
CREATE POLICY site_scope ON cable_schedule.route_history AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.mv_study_settings;
CREATE POLICY site_scope ON cable_schedule.mv_study_settings AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.fault_sources;
CREATE POLICY site_scope ON cable_schedule.fault_sources AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.protection_devices;
CREATE POLICY site_scope ON cable_schedule.protection_devices AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.cables;
CREATE POLICY site_scope ON cable_schedule.cables AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.change_log;
CREATE POLICY site_scope ON cable_schedule.change_log AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.fault_results;
CREATE POLICY site_scope ON cable_schedule.fault_results AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.cost_lines;
CREATE POLICY site_scope ON cable_schedule.cost_lines AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.discrimination_checks;
CREATE POLICY site_scope ON cable_schedule.discrimination_checks AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.mv_study_signoff;
CREATE POLICY site_scope ON cable_schedule.mv_study_signoff AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.supply_routes;
CREATE POLICY site_scope ON cable_schedule.supply_routes AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.sources;
CREATE POLICY site_scope ON cable_schedule.sources AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.supplies;
CREATE POLICY site_scope ON cable_schedule.supplies AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_revision(revision_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_revision(revision_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.route_segments;
CREATE POLICY site_scope ON cable_schedule.route_segments AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_supply_route(route_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_supply_route(route_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.terminations;
CREATE POLICY site_scope ON cable_schedule.terminations AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_cable(cable_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_cable(cable_id)));
DROP POLICY IF EXISTS site_scope ON cable_schedule.cable_tags;
CREATE POLICY site_scope ON cable_schedule.cable_tags AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_cable(cable_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_cable(cable_id)));
DROP POLICY IF EXISTS site_scope ON inspections.response_history;
CREATE POLICY site_scope ON inspections.response_history AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_inspection(inspection_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_inspection(inspection_id)));
DROP POLICY IF EXISTS site_scope ON inspections.signatures;
CREATE POLICY site_scope ON inspections.signatures AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_inspection(inspection_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_inspection(inspection_id)));
DROP POLICY IF EXISTS site_scope ON inspections.coc_validations;
CREATE POLICY site_scope ON inspections.coc_validations AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_inspection(inspection_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_inspection(inspection_id)));
DROP POLICY IF EXISTS site_scope ON inspections.certificates;
CREATE POLICY site_scope ON inspections.certificates AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_inspection(inspection_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_inspection(inspection_id)));
DROP POLICY IF EXISTS site_scope ON inspections.responses;
CREATE POLICY site_scope ON inspections.responses AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_inspection(inspection_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_inspection(inspection_id)));
DROP POLICY IF EXISTS site_scope ON inspections.photos;
CREATE POLICY site_scope ON inspections.photos AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_inspection(inspection_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_inspection(inspection_id)));
DROP POLICY IF EXISTS site_scope ON field.form_photos;
CREATE POLICY site_scope ON field.form_photos AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_site_form(form_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_site_form(form_id)));
DROP POLICY IF EXISTS site_scope ON field.form_signatures;
CREATE POLICY site_scope ON field.form_signatures AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_site_form(form_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_site_form(form_id)));
DROP POLICY IF EXISTS site_scope ON field.form_responses;
CREATE POLICY site_scope ON field.form_responses AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_site_form(form_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_site_form(form_id)));
DROP POLICY IF EXISTS site_scope ON field.form_response_history;
CREATE POLICY site_scope ON field.form_response_history AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_site_form(form_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_site_form(form_id)));
DROP POLICY IF EXISTS site_scope ON projects.tender_boq_items;
CREATE POLICY site_scope ON projects.tender_boq_items AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_tender(tender_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_tender(tender_id)));
DROP POLICY IF EXISTS site_scope ON projects.tender_requirements;
CREATE POLICY site_scope ON projects.tender_requirements AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_tender(tender_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_tender(tender_id)));
DROP POLICY IF EXISTS site_scope ON projects.tender_estimate_lines;
CREATE POLICY site_scope ON projects.tender_estimate_lines AS RESTRICTIVE FOR ALL
  USING (public.user_has_project_access(public.site_project_of_tender(tender_id)))
  WITH CHECK (public.user_has_project_access(public.site_project_of_tender(tender_id)));

DROP POLICY IF EXISTS site_scope ON projects.projects;
CREATE POLICY site_scope ON projects.projects AS RESTRICTIVE FOR ALL
  USING (
    public.user_has_project_access(id)
    OR EXISTS (SELECT 1 FROM public.user_organisations uo
               WHERE uo.organisation_id = projects.organisation_id AND uo.user_id = auth.uid() AND uo.is_active
                 AND (uo.role IN ('owner', 'admin') OR (uo.role = 'project_manager' AND projects.created_by = auth.uid())))
  )
  WITH CHECK (
    public.user_has_project_access(id)
    OR EXISTS (SELECT 1 FROM public.user_organisations uo
               WHERE uo.organisation_id = projects.organisation_id AND uo.user_id = auth.uid() AND uo.is_active
                 AND (uo.role IN ('owner', 'admin') OR (uo.role = 'project_manager' AND projects.created_by = auth.uid())))
  );
CREATE OR REPLACE FUNCTION public.user_can_see_profile(p_target uuid)
 RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER
 SET search_path TO 'public' SET row_security TO 'off'
AS $function$
  SELECT p_target = auth.uid()
    OR EXISTS (SELECT 1 FROM projects.project_members a JOIN projects.project_members b ON b.project_id = a.project_id
               WHERE a.user_id = auth.uid() AND a.is_active AND b.user_id = p_target AND b.is_active)
    OR EXISTS (SELECT 1 FROM public.user_organisations me JOIN public.user_organisations them ON them.organisation_id = me.organisation_id
               WHERE me.user_id = auth.uid() AND me.is_active AND me.role IN ('owner', 'admin')
                 AND them.user_id = p_target AND them.is_active)
$function$;
REVOKE ALL ON FUNCTION public.user_can_see_profile(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.user_can_see_profile(uuid) TO authenticated, service_role;

DROP POLICY IF EXISTS site_scope ON public.profiles;
CREATE POLICY site_scope ON public.profiles AS RESTRICTIVE FOR SELECT
  USING (public.user_can_see_profile(id));
CREATE OR REPLACE FUNCTION public.storage_site_access(p_bucket text, p_name text)
 RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER
 SET search_path TO 'public' SET row_security TO 'off'
AS $function$
DECLARE
  v_org  text := split_part(p_name, '/', 1);
  v_proj text := CASE WHEN p_bucket = 'jbcc-letters' THEN split_part(p_name, '/', 3) ELSE split_part(p_name, '/', 2) END;
  c_uuid CONSTANT text := '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
BEGIN
  IF v_org ~ c_uuid AND EXISTS (SELECT 1 FROM public.user_organisations uo
       WHERE uo.organisation_id = v_org::uuid AND uo.user_id = auth.uid() AND uo.is_active AND uo.role IN ('owner', 'admin')) THEN
    RETURN true;
  END IF;
  RETURN v_proj ~ c_uuid AND public.user_has_project_access(v_proj::uuid);
END;
$function$;
REVOKE ALL ON FUNCTION public.storage_site_access(text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.storage_site_access(text, text) TO authenticated, service_role;

DROP POLICY IF EXISTS site_scope_objects ON storage.objects;
CREATE POLICY site_scope_objects ON storage.objects AS RESTRICTIVE FOR ALL
  USING (CASE WHEN bucket_id IN ('drawings', 'project-documents', 'rfi-attachments', 'diary-attachments', 'snag-photos', 'coc-documents', 'qc-report-entries', 'jbcc-letters', 'cable-schedule-evidence') THEN public.storage_site_access(bucket_id, name) ELSE true END)
  WITH CHECK (CASE WHEN bucket_id IN ('drawings', 'project-documents', 'rfi-attachments', 'diary-attachments', 'snag-photos', 'coc-documents', 'qc-report-entries', 'jbcc-letters', 'cable-schedule-evidence') THEN public.storage_site_access(bucket_id, name) ELSE true END);
CREATE OR REPLACE FUNCTION public.custom_jwt_claims(event jsonb)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  _user_id uuid; _org_id uuid; _org_role text; _project_ids jsonb; _claims jsonb;
BEGIN
  _user_id := (event ->> 'user_id')::uuid;
  SELECT organisation_id, role INTO _org_id, _org_role FROM public.user_organisations
   WHERE user_id = _user_id AND is_active = true ORDER BY created_at ASC LIMIT 1;
  SELECT COALESCE(jsonb_agg(DISTINCT pm.project_id), '[]'::jsonb) INTO _project_ids
    FROM projects.project_members pm
    JOIN public.user_organisations uo ON uo.user_id = pm.user_id AND uo.organisation_id = pm.organisation_id
   WHERE pm.user_id = _user_id AND pm.is_active = TRUE AND uo.is_active = TRUE;
  _claims := event -> 'claims';
  IF _org_id IS NOT NULL THEN
    _claims := jsonb_set(_claims, '{org_id}', to_jsonb(_org_id::text));
  END IF;
  _claims := jsonb_set(_claims, '{project_ids}', _project_ids);
  _claims := jsonb_set(_claims, '{all_sites}', to_jsonb(COALESCE(_org_role IN ('owner', 'admin'), false)));
  RETURN jsonb_set(event, '{claims}', _claims);
END;
$function$;

NOTIFY pgrst, 'reload schema';
