// apps/web/src/lib/whatsapp/core-sync.contract.test.ts
// @vitest-environment node
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = resolve(__dirname, '../../../../..')
const CANON = resolve(ROOT, 'packages/shared/src/whatsapp/core.ts')
const EDGE = resolve(ROOT, 'apps/edge-functions/supabase/functions/_shared/whatsapp/core.ts')
export const GENERATED_HEADER =
  '// GENERATED by packages/shared/scripts/sync-whatsapp-core.mjs — DO NOT EDIT.\n' +
  '// Edit packages/shared/src/whatsapp/core.ts and re-run the script.\n'

describe('whatsapp core sync', () => {
  it('the edge copy is the canonical file behind the generated header, byte for byte', () => {
    const canon = readFileSync(CANON, 'utf8')
    const edge = readFileSync(EDGE, 'utf8')
    expect(edge).toBe(GENERATED_HEADER + canon)
  })
  it('the canonical file has no imports (Deno and Node must load it identically)', () => {
    expect(readFileSync(CANON, 'utf8')).not.toMatch(/^\s*import\s/m)
  })
})
