// packages/db/src/site-scope/generate.ts
import { RESOLVERS, GATED, type Gated, type Resolver } from './manifest'
import { ROLE_FUNCTIONS_SQL, PROJECTS_SQL, PROFILES_SQL, STORAGE_SQL, JWT_HOOK_SQL, FIXED_VERIFY } from './fixed.sql'

export function projectExpr(p: Gated['project']): string {
  return 'resolver' in p ? `public.site_project_of_${p.resolver}(${p.column})` : p.column
}

function resolverSql(r: Resolver): string {
  const body = 'resolver' in r.via
    ? `SELECT public.site_project_of_${r.via.resolver}(${r.via.column}) FROM ${r.table} WHERE id = p_id`
    : `SELECT project_id FROM ${r.table} WHERE id = p_id`
  const fn = `public.site_project_of_${r.name}(uuid)`
  return [
    `CREATE OR REPLACE FUNCTION public.site_project_of_${r.name}(p_id uuid)`,
    ` RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' SET row_security TO 'off'`,
    `AS $f$ ${body} $f$;`,
    `REVOKE ALL ON FUNCTION ${fn} FROM PUBLIC, anon;`,
    `GRANT EXECUTE ON FUNCTION ${fn} TO authenticated, service_role;`,
  ].join('\n')
}

function policySql(g: Gated): string {
  const e = `public.user_has_project_access(${projectExpr(g.project)})`
  return [
    `DROP POLICY IF EXISTS site_scope ON ${g.table};`,
    `CREATE POLICY site_scope ON ${g.table} AS RESTRICTIVE FOR ALL`,
    `  USING (${e})`,
    `  WITH CHECK (${e});`,
  ].join('\n')
}

/** Resolvers ordered so a resolver that calls another comes after it. */
function orderedResolvers(): Resolver[] {
  const done = new Set<string>(); const out: Resolver[] = []
  const visit = (r: Resolver) => {
    if (done.has(r.name)) return
    if ('resolver' in r.via) visit(RESOLVERS.find((x) => x.name === (r.via as { resolver: string }).resolver)!)
    done.add(r.name); out.push(r)
  }
  RESOLVERS.forEach(visit)
  return out
}

export function generateMigration(): string {
  const verify = [
    '-- @verify:begin',
    ...FIXED_VERIFY,
    ...RESOLVERS.map((r) => `-- function: public.site_project_of_${r.name}(uuid)`),
    ...RESOLVERS.map((r) => `-- sql: (SELECT NOT has_function_privilege('anon', 'public.site_project_of_${r.name}(uuid)', 'EXECUTE'))`),
    ...GATED.map((g) => `-- policy: site_scope ON ${g.table} RESTRICTIVE`),
    '-- @verify:end',
  ].join('\n')
  return [
    '-- Site-scoped access. GENERATED by scripts/db/site-scope/emit.ts from',
    '-- packages/db/src/site-scope/{manifest,fixed.sql}.ts. Do not edit by hand.',
    '-- Spec: docs/superpowers/specs/2026-10-01-site-scoped-access-design.md',
    verify,
    '',
    ROLE_FUNCTIONS_SQL.trim(),
    '',
    ...orderedResolvers().map(resolverSql),
    '',
    ...GATED.map(policySql),
    '',
    PROJECTS_SQL.trim(),
    PROFILES_SQL.trim(),
    STORAGE_SQL.trim(),
    JWT_HOOK_SQL.trim(),
    '',
    "NOTIFY pgrst, 'reload schema';",
    '',
  ].join('\n')
}
